nl-design-system/themes

.github/dependabot.yml, .ncurc.major.js
The comments and (additional) config used in #25 are now also used for ignoring versions with dependabot.
=> Chore: align dependabot config with ncurc

proprietary/buren-design-tokens/src/brand/buren/color.tokens.json, proprietary/buren-design-tokens/src/common/utrecht/focus.tokens.json, proprietary/buren-design-tokens/src/component/utrecht/button.tokens.json, proprietary/buren-design-tokens/src/component/utrecht/document.tokens.json, proprietary/buren-design-tokens/src/component/utrecht/form-input.tokens.json, proprietary/buren-design-tokens/src/component/utrecht/form-label.tokens.json, proprietary/buren-design-tokens/src/component/utrecht/form-select.tokens.json, proprietary/buren-design-tokens/src/component/utrecht/link.tokens.json, proprietary/buren-design-tokens/src/component/utrecht/paragraph.tokens.json, proprietary/buren-design-tokens/src/component/utrecht/textarea.tokens.json
The tokens in all other themes use the lightness as key, and in this package the tokens were in reverse lightness. So where before a color `hsl(h, s, 70%)` would have `"30": { ... }` as key, now it has `"70": { ... }` as key.
=> fix: use correct lightness values as design token name for Buren

.github/CODEOWNERS
Add [CODEOWNERS](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-syntax) file to enable requiring code owners to review for specific parts of the themes repo. 
I've also enabled `require code owner review before merging`
=> ci: add code owners file

packages/example-theme/figma/example.tokens.json
Was 0.125 em maar moest 1px zijn.
=> Text spacing fix

.github/workflows/continuous-deployment.yml, package.json
Somehow `--dry-run` was included during testing and merged.
=> ci: acutally release npm package, no dry run

package.json, packages/storybook/config/preview.js, packages/theme-toolkit/package.json, packages/theme-toolkit/src/component-stories-denhaag.jsx, packages/theme-toolkit/src/component-stories-util.js, pnpm-lock.yaml, proprietary/buren-design-tokens/src/component/den-haag/process-steps.tokens.json, proprietary/buren-design-tokens/src/component/den-haag/step-marker.tokens.json, proprietary/buren-design-tokens/src/component/utrecht/button.tokens.json, proprietary/buren-design-tokens/src/config.json
Deze PR voegt toe: 
- component 'process steps' van Den Haag Design System + Den Haag component CSS  
- story die process steps component gebruikt
- gebruik van die story via `config.json` van `buren-design-tokens` map
- tokens in `buren-design-tokens` map die specifiek voor process steps component zijn
- tokens in `buren-design-tokens` map die specifiek “step marker” zijn; deze worden door process steps gebruikt
Een visuele weergave daarvan:
~Het zet ook  de `--ci` flag in Playroom van Storybook, om te voorkomen dat dit proces automagisch een browservenster opent ([`--no-open` bestaat hiervoor ook vanaf 6.4.0](https://github.com/storybookjs/storybook/releases/tag/v6.4.0-alpha.23), maar lijkt in onze Storybook (6.5.16) niet te werken) (lmk als je dit liever in een losse PR hebt).~ (dit …
=> Add steps component and first version of Buren tokens for that component

.github/workflows/continuous-deployment.yml
apparently the validator does not support `nl` extensions, and none of the valid files pass the check
=> ci: temporarily disable publiccode.yml checking

.github/CODEOWNERS
A step in the right direction to remove the root `kernteam-sysadmin`.
=> ci: change default review team

packages/storybook/config/main.ts, packages/voorbeeld-design-tokens/documentation/breadcrumb-navigation/utrecht.stories.tsx
- Breadcrumb.stories.tsx -> breadcrumb-navigation/utrecht.stories.tsx
- add title to meta so the sidebar nests breadcrumb navigation properly and is ready for adding for example the RVO breadcrumb
=> chore: nest breadcrumb navigation

packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Tokens voor de Switch component toegevoegd tijdens Estafettemodeldag 2. Begonnen vanuit [Utrecht form toggle](https://nl-design-system.github.io/utrecht/storybook/?path=/story/css_css-form-toggle--design-tokens) maar gedurende ontwikkeling tokens aangepast ([vragen genoteerd](https://www.figma.com/design/shhwGcqPLi2CapK0P1zz8O?node-id=11982-21531#853314235)), vandaar nu als todo beschikbaar.
=> Switch tokens

.changeset/2024-08-15--jeff.md, packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Relates to ticket: https://github.com/nl-design-system/kernteam/issues/846
Overview of tokens that had the utrecht prefix and now have the voorbeeld prefix:
**Typography**
.document.strong.font-weight
**Colors**
.root.background-color
.document.subtle.color
.document.inverse.color
.document.inverse.background-color
.container.border-color
.line.border-color
.interaction.* (all)
.form-control.accent-color
.form-control.active.* (all)
.form-control.hover.* (all)
.form-control.disabled.accent-color
.feedback.informative.* (all)
.feedback.negative.* (all)
.feedback.positive.* (all)
**Size**
icon.functional.size
icon.toptask.size
**Border**
.container.border-width
.line.border-width
.form-control.active.border-width
.form-control.focus.border-width
.form-control.hover.border-width
**Focus** …
=> Common tokens split

.changeset/kwik-kwek-kwak.md, packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
- `paragraph-lead` to `paragraph.lead`
- `paragraph-small-print` to `paragraph.small`
=> fix: rename paragraph tokens

.husky/pre-commit, .lintstagedrc.json, lint-staged.config.cjs
Use `lint-staged.config.cjs` instead of `.lint-stagedrc.json`.
Run `prettier --ignore-unknown --write` for all files that Prettier can autofix. These fixes are added to the same commit instead of resulting in a new commit.
=> chore: fix lint-staged config

.markdownlint.json
Added `"MD041": false` to the markdownlint for themes repo.
=> update: markdownlint

.changeset/tear-injury-mold.md, packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Removed tokens that are available in code, but have no use in Figma:
- `.button.margin-block-end`
- `.button.margin-block-start`
=> fix: remove button tokens for margin

.changeset/koffie-thee-water.md, packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Changed name to align with code:
- `.accordion.body` to `.accordion.panel`
- `.accordion.button.icon.margin-inline` to `.accordion.button.gap`
Changed prefix from `.utrecht` to `.todo` for tokens that do not (yet) exist in code:
- `.accordion.border-radius`
- `.accordion.button.font-family`
- `.accordion.button.font-size`
- `.accordion.button.font-weight`
- `.accordion.button.line-height`
- `.accordion.button.expanded.background-color`
- `.accordion.button.expanded.border-color`
- `.accordion.button.expanded.color`
- `.accordion.section.border-color`
- `.accordion.section.border-block-end-width`
=> fix: align accordion tokens with code

.changeset/quaint-clearance-official.md, packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Added tokens that are available in code:
- `.alert.background-color`
- `.alert.border-color`
- `.alert.border-radius`
- `.alert.color`
- `.alert.content.row-gap`
- `.alert.message.row-gap`
- `.alert.icon.color`
Changed prefix from `.utrecht` to `.todo` for tokens that do not (yet) exist in code:
- `.alert.heading.font-family`
- `.alert.heading.font-size`
- `.alert.heading.font-weight`
- `.alert.heading.line-height`
Removed tokens that are available in code, but have no use in Figma:
- `.alert.margin-block-end`
- `.alert.margin-block-start`
=> fix: align alert tokens with code

.changeset/paragraph-choose-mountain.md, packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Changed prefix from .utrecht to .todo for tokens that do not (yet) exist in code:
- `.badge-counter.border-color`
- `.badge-counter.border-width`
- `.badge-counter.line-height`
=> fix: align badge-counter tokens with code

.changeset/gap-governor-fiction.md, packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Removed token that did not exist in code:
- `utrecht.blockquote.attribution.padding-block-start`
Changed prefix from `.utrecht` to `.todo` for tokens which do not (yet) exist in code:
- `.blockquote.row-gap`
- `.blockquote.attribution.font-family`
- `.blockquote.attribution.font-weight`
- `.blockquote.attribution.line-height`
- `.blockquote.content.font-family`
- `.blockquote.content.font-weight`
- `.blockquote.content.line-height`
=> fix: align blockquote tokens with code

.changeset/leave-place-negligence.md, packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
fix: focus.color was supported as a token in code of utrecht so get's its `utrecht.` prefix back.
=> fix: prefix of focus color token

.changeset/guide-musical-bloodshed.md, packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Changed prefix of `heading.color` token from `todo.` to `utrecht.` because it is available in code.
=> fix: prefix of heading color

.changeset/grave-think-goat.md, packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Removed margin tokens from Paragraph to align with other component tokens within Figma.
=> fix: align paragraph tokens with code

.changeset/shoot-forum-era.md, packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
- Renamed token `select.border-bottom-width` to `border-block-end-width`.
- Added token `select.min-block-size`.
- Removed token `select.invalid.color`.
Prefix from `.utrecht` to `.todo`
- `select.line-height`
- `select.icon.size`
- `select.focus.border-width`
- `select.hover.*`
=> fix: align select tokens with code

.changeset/date-plain-sugar.md, packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Prefix from `.utrecht` to `.todo`
- `drawer.header.label.font-family`
- `drawer.header.label.font-weight`
- `drawer.header.label.font-size`
- `drawer.header.label.line-height`
=> fix: change prefix of drawer header tokens

.changeset/charm-slump-rubbish.md, packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Removed margin tokens from headings 1 to 6 to align with other component tokens within Figma.
=> fix: removed margin tokens for headings 1 to 6

.changeset/age-cup-night.md, age-cup-night.md, packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Aligned ordered-list tokens with code.
Added token `ordered-list.item.padding-inline-start`
Removed tokens:
- `ordered-list.color`
- `ordered-list.font-family`
- `ordered-list.font-weight`
=> fix: align ordered-list  tokens with code

.changeset/enfix-witness-earthflax.md, packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Aligned form-field-error-message tokens with code.
Renamed token:
`.form-field-error-message.icon.margin-inline-end` to `.form-field-error-message.column-gap`
Prefix from `.utrecht` to `.todo`:
- `.form-field-error-message.column-gap`
- `.form-field-error-message.icon.size`
Added tokens:
- `.form-field-error-message.background-color`
- `.form-field-error-message.padding*` (all)
Reordered tokens for easier scanning.
=> fix: align form-field-error-message tokens with code

.changeset/last-perfume-momentum.md, packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Changed prefix from `.utrecht` to `.todo` for tokens that do not (yet) exist in code:
Additional states when checked:
- `.checkbox.checked.active.background-color`
- `.checkbox.checked.active.border-color`
- `.checkbox.checked.active.border-width`
- `.checkbox.checked.active.color`
- `.checkbox.checked.focus.background-color`
- `.checkbox.checked.focus.border-color`
- `.checkbox.checked.focus.border-width`
- `.checkbox.checked.focus.color`
- `.checkbox.checked.hover.background-color`
- `.checkbox.checked.hover.border-color`
- `.checkbox.checked.hover.border-width`
- `.checkbox.checked.hover.color`
- `.checkbox.checked.disabled.background-color`
- `.checkbox.checked.disabled.border-color`
- `.checkbox.checked.disabled.color`
Additional states when indeterminate:
- …
=> fix: align checkbox tokens with code

.changeset/hold-motorist-mug.md, packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Changed name of some breadcrumb tokens:
- `.breadcrumb.divider.color` to `.breadcrumb-nav.separator.color`.
- `.breadcrumb.divider.size` to `.breadcrumb-nav.separator.size`.
- `.breadcrumb.margin-inline` to `breadcrumb-nav.column-gap`.
- `.breadcrumb.link.icon.margin-inline` to `.breadcrumb-nav.link.icon.column-gap`.
=> fix: changed name of breadcrumb tokens

packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Prefixed status-badge tokens with `.todo` because the name of the component and token options differ to much with the code of Utecht.
https://nl-design-system.github.io/utrecht/storybook/?path=/story/css_css-status-badge--design-tokens
=> fix: prefix status-badge tokens with `.todo`.

.changeset/maid-ditch-shelf.md, packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Aligned textarea tokens with code.
Renamed token:
- `textarea.border-bottom-width` to `textarea.border-block-end-width`
Removed tokens:
- `textarea.hover.border-width`
- `textarea.focus.border-width`
Added token:
- `textarea.min-block-size`
- `textarea.invalid.border-block-end-width`
Prefix from `.utrecht` to `.todo`
- `textarea.focs.border-width`
- `textarea.hover.*`
Referenced to common form-control tokens.
=> fix: align textarea tokens with code

.changeset/shout-wheat-coast.md, packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Aligned unordered-list tokens with code.
Added token `unordered-list.item.padding-inline-start`
Removed tokens:
- `unordered-list.color`
- `unordered-list.font-family`
- `unordered-list.font-weight`
- `unordered-list.marker.border-color`
=> fix: align unordered-list tokens with code

.changeset/coin-ideal-coal.md, packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Renamed
- tokenset from `text input` to `textbox`.
Removed tokens:
- `textbox.hover.border-width`
- `textbox.focus.border-width`
Added token:
- `textbox.min-block-size`
- `textbox.invalid.border-block-end-width`
Prefix from `.utrecht` to `.todo`
- `textbox.focus.border-width`
- `textbox.hover.*`
Referenced to common form-control tokens.
=> fix: align textbox tokens with code

packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Renamed `voorbeeld.form-control.focus.border-width` to `utrecht.form-control.focus.border-width` as it was available in code
=> fix: rename prefix for form-control border-width

packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Didn't use the following tokens:
- `margin-block-start`
- `margin-block-end`
We didn't use these tokens because they are not supported in Figma.
=> feat: add pre-heading tokens

packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Also added todo tokens:
- `todo.badge-data.background-color`
- `todo.badge-data.border-radius`
- `todo.badge-data.font-family`
- `todo.badge-data.line-height`
- `todo.badge-data.font-size`
- `todo.badge-data.font-weight`
- `todo.badge-data.max-block-size`
- `todo.badge-data.max-inline-size`
- `todo.badge-data.min-block-size`
- `todo.badge-data.min-inline-size`
- `todo.badge-data.padding-block-end`
- `todo.badge-data.padding-inline-start`
- `todo.badge-data.text-decoration`
We have added these tokens because the Data badge will eventually receive fully independent tokens.
Depends on ["Badge data" component vervangen door "Data badge"](https://github.com/nl-design-system/utrecht/issues/2479).
=> feat: add badge data tokens

packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Also added new tokens:
- `utrecht.breadcrumb-nav.link.active.color`
- `utrecht.breadcrumb-nav.link.active.text-decoration`
- `utrecht.breadcrumb-nav.link.text-decoration`
And didn't use the following tokens:
- `utrecht.breadcrumb-nav.arrows.link.background-color`
- `utrecht.breadcrumb-nav.arrows.link.focus.background-color`
We didn't use these tokens because the documentation states the following:
> The "arrows appearance" is specific to the Municipality of Utrecht, we recommend to avoid this appearance for other organisations.
=> feat: add utrecht breadcrumb navigation tokens

packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
I alined sidenav tokens with code. But these still need to be added to the Den Haag component.
Renamed tokens
- `sidenav.link.icon.margin-inline` to `sidenav.link.column-gap`
- `sidenav.link.font-familiy` to `sidenav.item.font-familiy`
- `sidenav.link.font-weight` to `sidenav.item.font-weight`
- `sidenav.link.line-height` to `sidenav.item.line-height`
- `sidenav.link.font-size` to `sidenav.item.font-size`
Added tokens
- `sidenav.min-width`
- `sidenav.row-gap`
- `sidenav.list.padding-block-end`
- `sidenav.list.padding-block-start`
- `sidenav.list.padding-inline-start`
Prefix from `.denhaag` to `.todo`:
- `sidenav.link.icon.size`
- `sidenav.link.current.color`
- `sidenav.link.focus.color`
- `sidenav.link.focus.background-color`
- `sidenav.link.active.text-decoration`
- …
=> fix: align sidenav tokens with code

.changeset/update-nora-design-tokens.md, proprietary/nora-design-tokens/figma/figma.tokens.json, proprietary/nora-design-tokens/src/index.scss, proprietary/nora-design-tokens/style-dictionary.config.mjs
* Tokens die `large-vw` in hun path hebben worden nu als variabelen naar `theme-large-vw.css` en `variables-large-vw.css` geschreven. 
* De namen van deze tokens worden in deze bestanden herschreven zonder de `large-vw` aanduiding
* De tokens blijven ook nog als variabele bestaan met `large-vw` aanduiding in `theme.css` en `variables.css`
Dit maakt het mogelijk om tokens die specifiek bedoeld zijn voor een grotere viewport width te gebruiken in combinatie met een media-query, bijvoorbeeld als volgt:
`@import '@nl-design-system-community/nora-design-tokens/dist/theme-large-vw.css' (min-width: 992px);`
=> Large VW tokens naar apart css bestand schrijven

packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Added candidate tokens for Code Block.
Removed the following tokens:
- `nl.code-block.padding-block-start`
- `nl.code-block.padding-block-end`
- `nl.code-block.padding-inline-start`
- `nl.code-block.padding-inline-end`
Added the following tokens:
- `nl.code-block.padding-block`
- `nl.code-block.padding-inline`
- `nl.code-block.border-radius`
=> style: add candidate tokens for code block

packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Added candidate tokens for Data Badge. 
Didn't use the following tokens from the Badge component:
- `nl.data-badge.text-transform`
- `nl.data-badge.letter-spacing`
Added the following tokens:
- `nl.data-badge.min-block-size`
- `nl.data-badge.min-inline-size`
- `nl.data-badge.font-family` 
- `nl.data-badge.border-color`
- `nl.data-badge.border-width`
=> style: add candidate tokens for data badge

packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Added candidate tokens for Heading Group.
The Pre-heading is no longer a separate component; like the Subheading, it is now part of the Heading Group.
=> style: add candidate tokens for heading group

.changeset/nora-use-tokens-studio-transforms.md, proprietary/nora-design-tokens/style-dictionary.config.mjs, style-dictionary-config.js
Je kunt nu met de flag `useTokensStudioTransformGroup` aangeven of de tokens-studio transforms toegepast moeten worden op de verschillende platforms. Hiermee gaan de tokens-studio transforms werken, zoals:
* Transform colors to rgba() format
* Transform shadow "type" property "innerShadow" to "inset"
* Zie voor meer info: https://github.com/Tokens-studio/sd-transforms?tab=readme-ov-file#style-dictionary-transforms-for-tokens-studio
Daarnaast worden composite tokens automatisch naar de juiste shorthand value omgeschreven.
=> fix: correct 'transformGroups' to 'transformGroup' in SD config

packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
- Added Community Data Badge tokens of Utrecht.
- Removed todo Bagde Data tokens.
=> Added Community Data Badge tokens of Utrecht

.changeset/soul-tempt-tool.md, packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Add missing line-height token for Form Field Error Message
=> fix: add missing line-height token for Form Field Error Message

.changeset/patch-fur-pair.md, packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
- Removed margin tokens to align component with all other components within Figma.
- Changed color of Separator because of WCAG non-text-contrast.
=> feat: changed tokens for separator

.changeset/mayor-row-chop.md, packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
refactor: renamed Summary List to Form Summary
=> refactor: renamed Summary List to Form Summary

.changeset/eleven-suits-nail.md, packages/tokens-lib/src/design-tokens.ts
`nl.nldesignsystem.css-property-syntax` and
`nl.nldesignsystem.figma-implementation` are two new known extensions
=> chore: add new known extensions

packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Didn't use the following tokens:
- `nl.icon.inset-block-start`
- `nl.icon.baseline.inset-block-start`
=> style: add candidate tokens for icon

.changeset/mighty-beds-carry.md, packages/storybook/config/main.ts, proprietary/groningen-design-tokens/documentation/changelog.mdx
2 dingen:
- de package voor Groningen was niet gepubliceerd, ook al waren er tokens gewijzigd. Hierbij alsnog een changeset
- om het makkelijk te maken voor leveranciers van Groningen om te weten wat er is gewijzigd, heb ik [de changelog nu in Storybook gepubliceerd](https://themes-git-docs-groningen-changelog-nl-design-system.vercel.app/?path=/docs/groningen-changelog--docs)
=> docs: release Groningen changes

.changeset/hungry-pandas-refuse.md, packages/theme-toolkit/src/style-dictionary.test.ts, packages/tokens-lib/src/style-dictionary.test.ts, style-dictionary-config.js
This fixes the units but note that it does also transform the format of a few other tokens. Scroll down for more. Three test results had to have their expected output (a color hex) changed to lower case instead of upper case due to this. See the last commit.
```diff
-  --voorbeeld-typography-line-height-lg: 200%;
+  --voorbeeld-typography-line-height-lg: 2;
```
```diff
-  --utrecht-accordion-button-active-border-color: transparent;
-  --voorbeeld-color-dark-alpha-100: #0000001a;
+  --utrecht-accordion-button-active-border-color: rgba(0, 0, 0, 0);
+  --voorbeeld-color-dark-alpha-100: rgba(0, 0, 0, 0.1);
```
```diff
-  --voorbeeld-typography-font-family-code: Fira Code, Tahoma, Verdana, sans-serif;
+  --voorbeeld-typography-font-family-code: 'Fira Code', Tahoma, Verdana, sans-serif;
```
=> feat: enable tokens studio transform group for voorbeeld thema

packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Removed: `text-decotation`
Added:
- `text-decoration-thickness`
- `text-underline-offset`
- `font-size`
- `line-height`
=> feat: additional tokens for skip-link component

.changeset/beige-camels-think.md, packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
This is supposed to be temporary. When we have implemented the `px` to `rem` converter we can use px in design tokens JSON and ship `rem` to CSS files in `dist/`.
This makes sure we support WCAG for:
- https://nldesignsystem.nl/wcag/1.4.4
- https://nldesignsystem.nl/wcag/1.4.12
=> style: use `rem` for typography tokens in voorbeeld theme

packages/theme-toolkit/src/component-stories-utrecht.tsx
**Pull Request**
In deze pull request heb ik button tokens toegevoegd aan de theme builder:
**Button component**
**Button Primary Action component**
**Button Secondary Action component**
**Button Subtle component**
Hoe weet ik welke tokens ik moet gebruiken voor elke button-variant? Mijn bron is het [Storybook](https://nl-design-system.github.io/utrecht/storybook/?path=/docs/html_html-button--docs) van Gemeente Utrecht, waar je onderaan de pagina alle gebruikte en bestaande tokens voor een specifieke component en de verschillende staten van die component kunt vinden.
=> feat: add button tokens theme builder

.changeset/home-dip-sit.md, proprietary/groningen-design-tokens/figma/figma.tokens.json
open stad maakt geen gebruik van visited, wel van focus - zorgt nu voor een error wanneer iemand terug gaat naar pagina. Witte voorgrond tekst wordt dan overgenomen. Waarbij dan er een wit 'gat' valt in de pagina. Want we hanteren een witte achtergrond.
=> Link fix open stad/ groningen

packages/theme-toolkit/src/component-stories-utrecht.tsx
**Pull Request**
In deze pull request heb ik alert tokens toegevoegd aan de volgende states:
Hoe weet ik welke tokens ik moet gebruiken voor elke alert-variant? Mijn bron is het [Storybook](https://nl-design-system.github.io/utrecht/storybook/?path=/docs/css_css-alert--docs) van Gemeente Utrecht, waar je onderaan de pagina alle gebruikte en bestaande tokens voor een specifieke component en de verschillende staten van die component kunt vinden.
=> feat: add alert tokens to theme builder

packages/theme-toolkit/src/component-stories-utrecht.tsx
**Pull Request Code Block**
In deze PR heb ik `code-block` tokens toegevoegd aan de Theme Builder in het Purmerend-thema.
Hoe bepaal ik welke tokens ik moet gebruiken voor elke code-block-variant? In de [documentatie](https://nl-design-system.github.io/utrecht/storybook/?path=/docs/css_css-code-block--docs) van Utrecht vind je onderaan de pagina een overzicht van alle gebruikte tokens voor een specifieke component, inclusief de verschillende staten van die component. Dit maakt het gemakkelijk om de juiste tokens te identificeren.
=> feat: add code block tokens

packages/theme-toolkit/src/component-stories-utrecht.tsx
In deze PR heb ik `select` tokens toegevoegd aan de Theme Builder in het Purmerend-thema.
Hoe bepaal ik welke tokens ik moet gebruiken voor elke select-variant? In de [documentatie](https://nl-design-system.github.io/utrecht/storybook/?path=/docs/html_html-select--docs) van Utrecht vind je onderaan de pagina een overzicht van alle gebruikte tokens voor een specifieke component, inclusief de verschillende staten van die component. Dit maakt het gemakkelijk om de juiste tokens te identificeren.
=> feat: add select tokens

packages/theme-toolkit/src/component-stories-utrecht.tsx
**Pull Request Document**
In deze PR heb ik `document` tokens toegevoegd aan de Theme Builder in het Purmerend-thema.
Hoe bepaal ik welke tokens ik moet gebruiken voor elke document-variant? In de [documentatie](https://nl-design-system.github.io/utrecht/storybook-react/?path=/docs/react-document--docs) van Utrecht vind je onderaan de pagina een overzicht van alle gebruikte tokens voor een specifieke component, inclusief de verschillende staten van die component. Dit maakt het gemakkelijk om de juiste tokens te identificeren.
=> feat: add document tokens

packages/theme-toolkit/src/component-stories-utrecht.tsx
**Pull Request Textarea**
In deze PR heb ik `textarea` tokens toegevoegd aan de Theme Builder in het Purmerend-thema.
Hoe bepaal ik welke tokens ik moet gebruiken voor elke textarea-variant? In de [documentatie](https://nl-design-system.github.io/utrecht/storybook-react/?path=/docs/react-textarea--docs) van Utrecht vind je onderaan de pagina een overzicht van alle gebruikte tokens voor een specifieke component, inclusief de verschillende staten van die component. Dit maakt het gemakkelijk om de juiste tokens te identificeren.
=> feat: add textarea tokens

packages/theme-toolkit/src/component-stories-utrecht.tsx
**Pull Request Separator**
In deze PR heb ik `separator` tokens toegevoegd aan de Theme Builder in het Purmerend-thema.
Hoe bepaal ik welke tokens ik moet gebruiken voor elke saparator-variant? In de [documentatie](https://nl-design-system.github.io/utrecht/storybook-react/?path=/docs/react-separator--docs) van Utrecht vind je onderaan de pagina een overzicht van alle gebruikte tokens voor een specifieke component, inclusief de verschillende staten van die component. Dit maakt het gemakkelijk om de juiste tokens te identificeren.
=> feat: add separator tokens

packages/theme-toolkit/src/component-stories-utrecht.tsx
**Pull Request Textarea**
In deze PR heb ik `textbox` tokens toegevoegd aan de Theme Builder in het Purmerend-thema.
Hoe bepaal ik welke tokens ik moet gebruiken voor elke textbox-variant? In de [documentatie](https://nl-design-system.github.io/utrecht/storybook-react/?path=/docs/react-textbox--docs) van Utrecht vind je onderaan de pagina een overzicht van alle gebruikte tokens voor een specifieke component, inclusief de verschillende staten van die component. Dit maakt het gemakkelijk om de juiste tokens te identificeren.
=> feat: add textbox tokens

packages/theme-toolkit/src/component-stories-utrecht.tsx
**Pull Request Paragraph**
In deze PR heb ik `paragraph` tokens toegevoegd aan de Theme Builder in het Purmerend-thema.
Hoe bepaal ik welke tokens ik moet gebruiken voor elke paragraph-variant? In de [documentatie](https://nl-design-system.github.io/utrecht/storybook-react/?path=/docs/react-paragraph--docs) van Utrecht vind je onderaan de pagina een overzicht van alle gebruikte tokens voor een specifieke component, inclusief de verschillende staten van die component. Dit maakt het gemakkelijk om de juiste tokens te identificeren.
=> feat: add paragraph tokens

packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Didn't use the following tokens because they are not supported in Figma:
- `utrecht.pagination.margin-block-end`
- `utrecht.pagination.margin-block-start`
- `utrecht.pagination.distanced.margin-inline-start`
- `utrecht.pagination.relative-link.distanced.margin-inline-end`
- `utrecht.pagination.relative-link.distanced.margin-inline-start`
I also used the following todo tokens in the component in Figma, but they already existed:
- `todo.pagination.line-height`
- `todo.pagination.relative-link.active.background-color`
- `todo.pagination.relative-link.active.border-color`
- `todo.pagination.relative-link.active.color`
- `todo.pagination.relative-link.focus.background-color`
- `todo.pagination.relative-link.focus.color`
- `todo.pagination.page-link.active.background-color`
- …
=> feat: add utrecht pagination tokens

packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Also added the brand and common font token:
- `voorbeeld.typography.font-family.code`
- `voorbeeld.code.font-family`
And didn't use the following tokens from the Code block component:
- `margin-block-start`
- `margin-block-end`
- `margin-inline-start`
- `margin-inline-end`
We didn't use these tokens because they are not supported in Figma.
=> feat: add code, code block and code font tokens

packages/theme-toolkit/src/component-stories-utrecht.tsx
**Pull Request**
In deze pull request heb ik link tokens toegevoegd aan de theme-builder:
Hoe weet ik welke tokens ik moet gebruiken voor elke link-variant? Mijn bron is het [Storybook](https://nl-design-system.github.io/utrecht/storybook/?path=/docs/react_react-link--docs) van Gemeente Utrecht, waar je onderaan de pagina alle gebruikte en bestaande tokens voor een specifieke component en de verschillende staten van die component kunt vinden.
=> feat: add link tokens to theme builder

.changeset/stale-jokes-sell.md, proprietary/basis-design-tokens/figma/basis.tokens.json, proprietary/purmerend-design-tokens/figma/figma.tokens.json
Added focus `outline-style` dashed to Purmerend theme
=> feat: add outline style dashed to purmerend theme

.changeset/fifty-jars-shave.md, proprietary/basis-design-tokens/figma/basis.tokens.json, proprietary/purmerend-design-tokens/figma/figma.tokens.json
**Added `text-underline-offset` to `Link`** 
Volgens de voorbeeld in Gemeente Utrecht is de underline offset 3px. 
In progress ⬇️
**Added `underline-thickness` hover state to `Link`**
Design token name `utrecht.link.hover.text-decoration-thickness` (3px) geeft aan token reference could not be found, daarom staat het gewoon hardcoded in als `3px`
=> feat: add text underline offset to link Purmerend theme

.github/workflows/continuous-deployment.yml
Switch from the legacy branch based workflow to deploy to GitHub Pages to the more modern workflow based one.
Add concurrency for builds.
Closes #945
=> ci: use GitHub Actions workflow for GitHub Pages

packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
As discussed with Robbert and Jeffrey during the Figma hygiene review, all `focus` tokens for Help Wanted components (with prefix `todo`) have been updated to `focus-visible`.
This update has been applied to the following components:
- Breadcrumb Navigation
- Case Card
- Checkbox
- Contact Timeline
- Page Number Navigation
- Progress List
- Side Navigation
- Switch
=> chore: rename focus tokens to focus-visible

packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Added the following tokens to support suffix for Form Field Label todo component:
- `todo.form-field-label.suffix.color`
- `todo.form-field-label.suffix.font-weight`
- `todo.form-field-label.column-gap`
=> Feat: Add tokens to support suffix for Form Field Label todo component

npmpackagejsonlint.config.cjs
Make running npm-package-json-lint fast once more. This solution works because proprietary packages all live at `proprietary/*` and not nested any deeper.
=> fix: npm-package-json-lint

packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
- Renamed `todo.form-field-label.suffix` to `todo.form-field-label-suffix`.
- Removed `todo.sidenav.link.text-decoration` and `denhaag.sidenav.link.focus-visible.text-decoration` (which did not exist)
=> Fix: Renamed suffix tokens and removed sidenav tokens

packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Renamed
`todo.progress-list.step-marker.nested.figma.inset-block-start`
to
`todo.progress-list.step-marker.nested.inset-block-start`
=> fix: renamed token of progress-list

packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Emma found out we did not use the correct name. We changed Button Group to Action Group in our documentation. But we have not yet done this in the Token Studio tokenset. This PR will fix it.
=> Fix: Button group renamed to Action group

.changeset/hocus-pocus-pas.md, packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
This PR relates to: https://github.com/nl-design-system/documentatie/issues/2114
It will split up component token sets per organisation, making it easier to copy and paste a token set of a specific component from an organisation.
Component tokens affected:
- Breadcrumb Navigation
- Code
- Code Block
- Color Sample
- Data Badge
- Drawer
- Form Field Label
- Heading
- Link
- Mark
- Number Badge
- Page Number Badge
- Paragraph
- Progress List
- Skip Link
P.S. Changed the order of tokens for most of the tokensets while I was at it.
=> Refactor: split tokens per org

.changeset/bax-top-step.md, packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
De volgende tokens zijn toegevoegd aan de Heading component.
- `nl.heading.level-1.margin-block-start`
- `nl.heading.level-1.margin-block-end`
- `nl.heading.level-2.margin-block-start`
- `nl.heading.level-2.margin-block-end`
- `nl.heading.level-3.margin-block-start`
- `nl.heading.level-3.margin-block-end`
- `nl.heading.level-4.margin-block-start`
- `nl.heading.level-4.margin-block-end`
- `nl.heading.level-5.margin-block-start`
- `nl.heading.level-5.margin-block-end`
- `nl.heading.level-6.margin-block-start`
- `nl.heading.level-6.margin-block-end`
=> feat(heading-tokens): add new tokens

.changeset/link-list-this.md, packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Waarde van token `utrecht.link-list.link.column-gap` is gewijzigd naar brand token `voorbeeld.space.text.beetle`.
=> style: link-list token value

.changeset/README.md, .prettierignore, prettier.config.cjs
- Add a template for major, minor, and patch changes
- Explain how to find the name of a package
- Hopefully simplify the templates a bit
- Add a Prettier exception for `.changeset/README.md`
=> docs: improve .changetset/README.md

.changeset/text-in-area.md, packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Tokenset `textarea` hernoemd naar `text-area` zodat de schrijfwijze van deze tokenset overeenkomt met de gekozen naamgeving voor dit component.
=> fix: rename tokenset textarea to text-area

packages/start-design-tokens/figma/start.tokens.json
- Tokenset `dark-mode` onder `components` tokenset geplaatst.
- Tokenset `dark-mode` hernoemd naar `color-scheme-dark/common`
- Nieuwe tokenset toegevoegd `color-scheme-dark/components/progress-list/todo` met 1 enkele token om de achtergrond van de current state meer contrast te geven.
=> feat: color-scheme-dark setup

.changeset/focus-swap-color.md, packages/start-design-tokens/figma/start.tokens.json
De waarde van de volgende tokens zijn gewijzigd:
- `basis.focus.outline-color` naar `#0b0c0c`
- `basis.focus.inverse.outline-color` naar `#ffffff`
=> Waarde van 'focus-outline-color' en 'box-shadow-color' omgekeerd

.changeset/link-list-weight.md, packages/start-design-tokens/figma/start.tokens.json
Token `utrecht.link-list.font-weight` is hernoemd naar `utrecht.link-list.link.font-weight` in Link List component.
=> fix: Link List font-weight token hernoemd

.changeset/link-list-voorbeeld.md, packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Token `utrecht.link-list.font-weight` is hernoemd naar `utrecht.link-list.link.font-weight` in Link List component.
=> fix: Link List font-weight token hernoemd - Voorbeeld

packages/voorbeeld-design-tokens/documentation/form-field-description/utrecht-form-field-description.stories.tsx
Community Stappenplan: Organisaties -> Voeg de story toe aan de Components sectie in Storybook.
Onderdeel van https://github.com/nl-design-system/kernteam/issues/1515
Preview: https://themes-git-feat-add-utrecht-form-field-a07496-nl-design-system.vercel.app/?path=/story/utrecht-form-field-description--utrecht-theme
=> feat: add utrecht form field description stories

.changeset/button-action-voorbeeld.md, packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
De volgende tokens zijn hernoemd in Action Group component:
- `utrecht.button-group.background-color` naar `utrecht.action-group.background-color`
- `utrecht.button-group.column-gap` naar `utrecht.action-group.column-gap`
- `utrecht.button-group.padding-block-end` naar `utrecht.action-group.padding-block-end`
- `utrecht.button-group.padding-block-start` naar `utrecht.action-group.padding-block-start`
- `utrecht.button-group.row-gap` naar `utrecht.action-group.row-gap`
=> fix: rename button-group to action-group - Voorbeeld

.changeset/button-to-action.md, packages/start-design-tokens/figma/start.tokens.json
De volgende tokens zijn hernoemd in Action Group component:
- `utrecht.button-group.background-color` naar `utrecht.action-group.background-color`
- `utrecht.button-group.column-gap` naar `utrecht.action-group.column-gap`
- `utrecht.button-group.padding-block-end` naar `utrecht.action-group.padding-block-end`
- `utrecht.button-group.padding-block-start` naar `utrecht.action-group.padding-block-start`
- `utrecht.button-group.row-gap` naar `utrecht.action-group.row-gap`
=> fix: rename button-group to action-group

.changeset/note-border-voorbeeld.md, packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
De waarde van de volgende tokens zijn gewijzigd:
- `utrecht.spotlight-section.border-width` naar `0px`.
- `utrecht.spotlight-section.info.border-width` naar component token `utrecht.spotlight-section.border-width`.
- `utrecht.spotlight-section.error.border-width` naar component token `utrecht.spotlight-section.border-width`.
- `utrecht.spotlight-section.ok.border-width` naar component token `utrecht.spotlight-section.border-width`.
- `utrecht.spotlight-section.warning.border-width` naar component token `utrecht.spotlight-section.border-width`.
=> Waarde van Spotlight Section (Note) border-width aangepast - Voorbeeld

.changeset/sidenav-to-side-nav-voorbeeld.md, packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
De volgende tokens zijn hernoemd in Side Navigation component:
- `denhaag.sidenav.min-width` naar `denhaag.side-navigation.min-width`
- `denhaag.sidenav.row-gap` naar `denhaag.side-navigation.row-gap`
- `denhaag.sidenav.item.font-family` naar `denhaag.side-navigation.item.font-family`
- `denhaag.sidenav.item.font-size` naar `denhaag.side-navigation.item.font-size`
- `denhaag.sidenav.item.font-weight` naar `denhaag.side-navigation.item.font-weight`
- `denhaag.sidenav.item.line-height` naar `denhaag.side-navigation.item.line-height`
- `denhaag.sidenav.item.margin-block-end` naar `denhaag.side-navigation.item.margin-block-end`
- `denhaag.sidenav.item.margin-block-start` naar `denhaag.side-navigation.item.margin-block-start`
- `denhaag.sidenav.item.margin-inline-end` naar …
=> fix: rename sidenav to side-navigation - Voorbeeld
