nl-design-system/themes

- documentation/open-forms/README.md
- documentation/open-forms/color.stories.mdx
- documentation/open-forms/config.json
- documentation/open-forms/readme.stories.mdx
- package-lock.json
- package.json
- packages/theme-switcher/src/generate-json.js
- packages/theme-switcher/src/index.js
Initial work on adding our design tokens to the NL DS documentation.
**Changes**
* Added `@open-formulieren/design-tokens` dependency
* Added documentation configuration
* Export (some of) the color design tokens in Storybook
* Documented design-tokens repository in the README
* Added Open Forms theme to the theme switcher
> Adds Open Formulieren theme to the documentation and theme switcher

- packages/example-theme/figma/example.tokens.json
> paragraph update

- packages/example-theme/figma/example.tokens.json
Paragraph component en tokens opgesplitst.
> Vrijdagmiddag

- packages/example-theme/figma/example.tokens.json
Headings opgesplitst. Avatar tokens toegevoegd
> Headings opgesplits

- packages/example-theme/figma/example.tokens.json
nl.common.transparent.border-color vervangen voor simpelweg transparent
> nl.common.transparent.border-color vervangen

- packages/example-theme/figma/example.tokens.json
Losse sets voor components terug gebracht naar 1 set voor component tokens.
> 1 set voor component tokens

- packages/example-theme/figma/example.tokens.json
Waarde van brand shadow token aangepast
> Token namen versimpeld

- packages/example-theme/figma/example.tokens.json
Lijkt me handig om nog wat extra grote spacing tokens te hebben voor pagina layout.
> Extra grote spacing toegevoegd

- packages/example-theme/figma/example.tokens.json
- Source Serif en Sans Pro als font
- Font sizes bijgewerkt
- Spacing met dierennamen
> Token update 24 jan

- packages/example-theme/figma/example.tokens.json
- Extra common tokens
- Dark mode tokens er voor nu uit
> Common update 1

- packages/example-theme/figma/example.tokens.json
> Terug gezet

- packages/theme-toolkit/src/component-stories-utrecht.jsx
- proprietary/amsterdam-design-tokens/src/component/utrecht/checkbox.tokens.json
- proprietary/amsterdam-design-tokens/src/component/utrecht/heading.tokens.json
- proprietary/amsterdam-design-tokens/src/component/utrecht/paragraph.tokens.json
- proprietary/amsterdam-design-tokens/src/component/utrecht/radio-button.tokens.json
- proprietary/amsterdam-design-tokens/src/component/utrecht/select.tokens.json
- proprietary/amsterdam-design-tokens/src/config.json
- proprietary/amsterdam-design-tokens/src/index.scss
laatste veranderingen voor het amsterdam thema.
Utrecht react componenten.
Hoeft alleen nog checkbox en radio button tokens verandert worden
> Amsterdam thema fix

- packages/example-theme/figma/example.tokens.json
Kleurpalette aangepast tbv darkmode support
> Kleurpalette aangepast

- packages/example-theme/figma/example.tokens.json
Icon size op common niveau laten verwijzen naar icon size brand niveau (ipv algemene sizing).
> Common icon size

- proprietary/rotterdam-design-tokens/src/component/utrecht/form-control.tokens.json
- proprietary/rotterdam-design-tokens/src/component/utrecht/form-field-error-message.tokens.json
- proprietary/rotterdam-design-tokens/src/component/utrecht/form-field.tokens.json
- max-inline-size voor form-controll to 15%
- form-field-error-message to red
> Rotterdam form field tokens changes

- packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Meer ruimte tussen icoon en label bij Accordion
> Accordion spacing fix

- packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Iets meer transparantie op backdrop
> 21-12-2023

- packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Tokens voorzien van todo prefix na bugfix Token Studio.
> todo prefix doorgevoerd

- packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Plus een kleine wijziging in de waarde van de smallest icon size.
> Tokenset voor Task-list

- packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
> not-checked

- packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
> style: restore `utrecht.form-field-error-message` and `form-field-description` tokens

- .github/workflows/continuous-deployment.yml
> fix: JamesIves/github-pages-deploy-action version

- packages/theme-toolkit/package.json
- packages/theme-toolkit/src/ComponentTokensSection.jsx
- packages/theme-toolkit/src/ComponentTokensTable.jsx
- packages/theme-toolkit/src/CopyButton.jsx
- packages/theme-toolkit/src/ExampleTokensCSS.jsx
- packages/theme-toolkit/src/ExampleTokensJSON.jsx
- packages/theme-toolkit/src/design-tokens.js
- pnpm-lock.yaml
Make themes-toolkit publishable
> feat: add ComponentTokensSection

- packages/theme-toolkit/package.json
- packages/theme-toolkit/rollup.config.mjs
- packages/theme-toolkit/src/index.mjs
- pnpm-lock.yaml
Make ComponentTokensSection available as a component.
> feat: add build script to theme-toolkit

- packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Zoals besproken in [deze PR](https://github.com/nl-design-system/themes/pull/542/files). Konden Form field, form field error message en form field description terug naar community status.
> 3 componenten terug naar community status

- packages/voorbeeld-design-tokens/documentation/Breadcrumb.stories.tsx
- packages/voorbeeld-design-tokens/documentation/Button.stories.tsx
- packages/voorbeeld-design-tokens/documentation/Checkbox.stories.tsx
- packages/voorbeeld-design-tokens/documentation/Fieldset.stories.tsx
- packages/voorbeeld-design-tokens/documentation/Heading1.stories.tsx
- packages/voorbeeld-design-tokens/documentation/Heading2.stories.tsx
- packages/voorbeeld-design-tokens/documentation/Heading3.stories.tsx
- packages/voorbeeld-design-tokens/documentation/Heading4.stories.tsx
- packages/voorbeeld-design-tokens/documentation/Heading5.stories.tsx
- packages/voorbeeld-design-tokens/documentation/Heading6.stories.tsx
- packages/voorbeeld-design-tokens/documentation/OrderedList.stories.tsx
- packages/voorbeeld-design-tokens/documentation/Paragraph.stories.tsx
- packages/voorbeeld-design-tokens/documentation/RadioButton.stories.tsx
- packages/voorbeeld-design-tokens/documentation/StatusBadge.stories.tsx
- packages/voorbeeld-design-tokens/documentation/Switch.stories.tsx
- packages/voorbeeld-design-tokens/documentation/TextInput.stories.tsx
- packages/voorbeeld-design-tokens/documentation/Textarea.stories.tsx
- packages/voorbeeld-design-tokens/documentation/UnorderedList.stories.tsx
Add an explicit ID to the components in packages/voorbeeld-design-tokens
> fix: add component IDs

- packages/storybook/config/main.ts
- packages/voorbeeld-design-tokens/documentation/breadcrumb-navigation/breadcrumb-navigation-utrecht.stories.tsx
- packages/voorbeeld-design-tokens/documentation/button/utrecht-button.stories.tsx
- packages/voorbeeld-design-tokens/documentation/checkbox/utrecht-custom-checkbox.stories.tsx
- packages/voorbeeld-design-tokens/documentation/fieldset/utrecht-form-fieldset.stories.tsx
- packages/voorbeeld-design-tokens/documentation/heading-1/utrecht-heading-1.stories.tsx
- packages/voorbeeld-design-tokens/documentation/heading-2/utrecht-heading-2.stories.tsx
- packages/voorbeeld-design-tokens/documentation/heading-3/utrecht-heading-3.stories.tsx
- packages/voorbeeld-design-tokens/documentation/heading-4/utrecht-heading-4.stories.tsx
- packages/voorbeeld-design-tokens/documentation/heading-5/utrecht-heading-5.stories.tsx
- packages/voorbeeld-design-tokens/documentation/heading-6/utrecht-heading-6.stories.tsx
- packages/voorbeeld-design-tokens/documentation/ordered-list/utrecht-ordered-list.stories.tsx
- packages/voorbeeld-design-tokens/documentation/paragraph/utrecht-paragraph.stories.tsx
- packages/voorbeeld-design-tokens/documentation/radio-button/utrecht-radio-button.stories.tsx
- packages/voorbeeld-design-tokens/documentation/status-badge/utrecht-badge-status.stories.tsx
- packages/voorbeeld-design-tokens/documentation/switch/utrecht-form-toggle.stories.tsx
- packages/voorbeeld-design-tokens/documentation/text-input/utrecht-textbox.stories.tsx
- packages/voorbeeld-design-tokens/documentation/textarea/utrecht-textarea.stories.tsx
- packages/voorbeeld-design-tokens/documentation/unordered-list/utrecht-unordered-list.stories.tsx
- Rename `id` to the component name for the organisation
- Add `title` with the NLDS name for the component
- Move and rename stories file:
- Use `<nlds-name>` for the directory
- Use `<id>` (organisation component name) for the filename of the stories file
> chore: restructure components

- packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Vanuit ticket: https://github.com/nl-design-system/kernteam/issues/798
> Tokens gelijk trekken

- packages/voorbeeld-design-tokens/documentation/form-field/utrecht-form-field.stories.tsx
> feat: add utrecht form field

- packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
- packages/voorbeeld-design-tokens/package.json
- packages/voorbeeld-design-tokens/style-dictionary.config.js
- packages/voorbeeld-design-tokens/style-dictionary.mjs
- pnpm-lock.yaml
- style-dictionary-config.js
Read more at https://docs.tokens.studio/convert-to-dtcg-format
> Convert to W3C DTCG format

- .changeset/appel-banaan-kiwi.md
- packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
`counter-badge` to `badge-counter`
> fix: rename counter-badge

- .changeset/spokesperson-tree-offer.md
- packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Aligned link tokens with code.
> fix: align link tokens with code

- .changeset/elaborate-insist-monkey.md
- packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Aligned link-list tokens with code.
> fix: align link-list tokens with code

- .changeset/humor-truck-chord.md
- packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
- Renamed token and tokenset `radio` to `radio-button`.
- Renamed token `radio-button.dot.size` to `radio-button.icon.size`.
- Removed token `radio-button-border-radius`.
> fix: align radio-button tokens with code

- packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Renamed `badge-counter` to `number-badge` as was done in utrecht code during Estafettemodel dag.
Pas mergen wanneer bij Utrecht de code is geupdate: https://github.com/nl-design-system/utrecht/pull/2482
> fix: rename `badge-counter` to `number-badge`

- .changeset/tail-scale-angle.md
- packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Add missing token for invalid border-block-end-width.
> feat: add missing token for invalid border-block-end-width

- packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
- changed prefix `radiobutton.checked.disabled.*`
- removed `table.row.background-color`
> changed prefix radiobutton and removed table row token.

- packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Added the utrecht Mark tokens.
> feat: add mark tokens

- packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Added the utrecht Color sample tokens.
> feat: add color sample tokens

- .changeset/dive-help-mercy.md
- packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Changed the value of `padding-inline-start` tokens.
> fix: changed value of ordered and unordered list tokens

- packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Added todo tokens for the Progress List.
This component is based on the Process Steps component from The Hague.
> add progress list to do tokens

- packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Added case card tokens with `to do` prefix.
> feat: add case card tokens

- .changeset/polite-trees-grin.md
- packages/theme-toolkit/package.json
- packages/theme-toolkit/src/TokensDownloadLink.tsx
- packages/theme-toolkit/src/style-dictionary-util.ts
- packages/theme-toolkit/src/style-dictionary.d.ts
- pnpm-lock.yaml
- proprietary/nora-design-tokens/documentation/design-tokens.mdx
Context: https://codefornl.slack.com/archives/C7KDQRXMZ/p1729586549730989?thread_ts=1729233228.359139&cid=C7KDQRXMZ
Download linkje toegevoegd bij NORA
https://themes-git-feat-tokens-download-link-nl-design-system.vercel.app/?path=/docs/nora-design-tokens--docs
> feat: add `<TokensDownloadLink>` component

- .changeset/orange-frogs-hang.md
- packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
This PR create the first candidate tokens with 'Voorbeeld theme' prefixed with `nl` for paragraph, link, mark and color sample.
> style: candidate tokens for paragraph, link, mark and color sample

- .changeset/nora-tokens-update-2.md
- proprietary/nora-design-tokens/figma/figma.tokens.json
* Tokens voor het Footer component toegevoegd
* Tokens voor Page Section aangepast zodat deze schaalt tot min-width: 992px
> Nora token updates

- .github/dependabot.yml
- .ncurc.major.cjs
- package.json
- pnpm-lock.yaml
- update package.json#packageManager and include hash
- align @types/node with the node version in the repo
> chores: packagemanager + @types/node

- .changeset/nora-design-tokens-update.md
- proprietary/nora-design-tokens/figma/figma.tokens.json
Tokens toegevoegd voor nieuwe componenten
> Nora design tokens updates

- proprietary/basis-design-tokens/figma/basis.tokens.json
Samen met Marwa geprobeerd de voorgestelde spacing token wijzigingen door te voeren via Token Studio.
> Changed spacing token naming and values

- packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
- Added candidate tokens for paragraph.
- Changed the order of some tokens.
> style: add candidate tokens for paragraph

- packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
- Added candidate tokens for skip link.
- Changed the order of some tokens.
- Removed some todo tokens.
> style: add candidate tokens for skip link

- packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Added candidate tokens for Code.
> style: add candidate tokens for code

- packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Added candidate tokens for Separator.
> style: add candidate tokens for separator

- packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
- Added Community Heading tokens of Amsterdam.
- Changed the order so Candidate tokens are on top.
> Added Community Heading tokens of Amsterdam

- packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Added candidate tokens for Number Badge.
> style: add candidate tokens for number badge

- packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Changed the order of the design tokens.
- Candidate tokens first
- Tokens alphabetically
> Changed order of tokens

- packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
- Moved community tokens for heading 1 to 6 to separate tokensets.
- Added candidate tokens for heading 1 to 6.
- Changed order of tokens.
> style: candidate tokens for heading 1 to 6

- proprietary/purmerend-design-tokens/figma/figma.tokens.json
toevoegen van font-family op root aan Purmerend theme
> font-family op root aan Purmerend theme

- .changeset/sour-zoos-lay.md
> docs: add changeset purmerend design token

- packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Dit betreft een aanpassing aan de hand van deze PR:
https://github.com/nl-design-system/utrecht/pull/2557
~~Dit is de opzet zoals besproken met Aline. Echter twijfel ik of dit nu is zoals het ook in code werkt. Graag even overleggen.~~
Overleg gehad. [Schetje besproken](https://www.figma.com/design/fy08SZpZmqx6ljLwvA3Woe/NLDS---Schetsboek?node-id=4519-401). We zijn er over uit dat het niet ideaal is maar voor nu gaan we zo door. Bij Candidate nog eens goed naar kijken.
> Add color token for Radio Button

- packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Added Community Action tokens of Den Haag
> style: add community action tokens of den haag

- packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Added Community File tokens of Den Haag
> style: add community file tokens of den haag

- packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
- Added additional tokens for Heading component.
- Referenced them from Heading 1/6 components.
> style: added additional tokens for Heading component

- packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
This PR will change the color values of the Mark component.
> style: change color of mark component

- packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
Added `color` token for placeholder link.
> feat: additional tokens for link component

- packages/components-react/design-tokens-table-react/src/TokenTypeIcon.tsx
text-decoration-line, text-decoration-thickness, text-underline-offset, text-underline-style
> feat: add 4 new design token types

- packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
This PR will add the design tokens of the [Form Label tokens of Utrecht](https://nl-design-system.github.io/utrecht/storybook/?path=/docs/css_css-form-label--docs) to the JSON.
> Add Form Field Label community tokens of Utrecht

- packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
This PR will remove the premature design tokens for candidate components that are not (yet) available in code. Removed tokens of:
- Heading 1 to 6
- Heading Group
- Icon
- Separator
> Removed premature candidate tokens.

- packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
This PR will change the tokens types of `spacing`, `sizing`, `borderRadius` and `borderWidth` to `dimension`.
> feat: use the dimension token type

- .changeset/big-bap-boop.md
- packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
De volgende tokens zijn toegevoegd aan de Paragraph component.
- `nl.paragraph.margin-block-start`
- `nl.paragraph.margin-block-end`
- `nl.paragraph.lead.margin-block-start`
- `nl.paragraph.lead.margin-block-end`
> feat(paragraph-tokens): add new tokens

- .changeset/wit-ruimte-reis.md
- packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
"[code-only]" aan description van margin tokens toegevoegd.
> feat(paragraph-tokens): add description

- .changeset/name-your-type.md
- packages/ma-design-tokens/src/tokens.json
Added the $ to the "type" metadata to align with the W3C DTCG format.
> fix: add $ to type metadata

- packages/ma-design-tokens/src/tokens.json
changed: yellow, orange and neutral hues
> changed-new-hues

- packages/start-design-tokens/README.md
- packages/start-design-tokens/figma/start.tokens.json
- packages/start-design-tokens/package.json
Add a new minimal @nl-design-system-unstable/start-design-tokens package
> feat: add start-design-tokens

- packages/start-design-tokens/figma/start.tokens.json
Door de tokens name toe te voegen kunnen we leuke dingen doen met de naam van een organisatie. In dit geval Start of Voorbeeld
> feat: add name token

- packages/start-design-tokens/figma/start.tokens.json
Helaas pindakaas. Misschien komt dit later nog wel een keer.
> Remove name token

- packages/theme-toolkit/package.json
- packages/theme-toolkit/src/component-stories-denhaag.tsx
- packages/theme-toolkit/src/component-stories-util.ts
- packages/voorbeeld-design-tokens/documentation/case-card/denhaag-case-card.stories.tsx
- packages/voorbeeld-design-tokens/package.json
- pnpm-lock.yaml
Part of https://github.com/nl-design-system/kernteam/issues/1370
> feat: add den haag case card to themes and visual regression test

- packages/theme-toolkit/package.json
- packages/theme-toolkit/src/component-stories-ams.tsx
- packages/theme-toolkit/src/component-stories-util.ts
- packages/voorbeeld-design-tokens/documentation/page-footer/ams-page-footer.stories.tsx
- packages/voorbeeld-design-tokens/package.json
- pnpm-lock.yaml
Part of https://github.com/nl-design-system/kernteam/issues/1367
Preview: https://themes-git-feat-add-amsterdam-page-foot-0843e0-nl-design-system.vercel.app/?path=/story/ams-page-footer--amsterdam-theme
> feat: add amsterdam page footer to themes and visual regression test

- .changeset/knee-crowd-uncle.md
- packages/start-design-tokens/figma/start.tokens.json
De tokens van Page Footer component van Amsterdam zijn toegevoegd.
> feat: add ams page-footer tokens

- .changeset/druk-actief-over.md
- packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
De volgende tokens zijn toegevoegd aan Button component:
- `utrecht.button.pressed.background-color`
- `utrecht.button.pressed.border-color`
- `utrecht.button.pressed.color`
- `utrecht.button.primary-action.pressed.background-color`
- `utrecht.button.primary-action.pressed.border-color`
- `utrecht.button.primary-action.pressed.color`
- `utrecht.button.secondary-action.pressed.background-color`
- `utrecht.button.secondary-action.pressed.border-color`
- `utrecht.button.secondary-action.pressed.color`
- `utrecht.button.subtle.pressed.background-color`
- `utrecht.button.subtle.pressed.border-color`
- `utrecht.button.subtle.pressed.color`
> feat: tokens voor pressed state toegevoegd aan button component

- .changeset/margin-token-voorbeeld.md
- packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
De volgende tokens zijn toegevoegd aan Action Group component:
- `utrecht.action-group.margin-block-end`
- `utrecht.action-group.margin-block-start`
De volgende tokens zijn toegevoegd aan Alert component:
- `utrecht.alert.margin-block-end`
- `utrecht.alert.margin-block-start`
De volgende tokens zijn toegevoegd aan Blockquote component:
- `utrecht.blockquote.margin-block-end`
- `utrecht.blockquote.margin-block-start`
- `utrecht.blockquote.margin-inline-end`
- `utrecht.blockquote.margin-inline-start`
De volgende tokens zijn toegevoegd aan Code Block component:
- `utrecht.code-block.margin-block-end`
- `utrecht.code-block.margin-block-start`
- `utrecht.code-block.margin-inline-end`
- `utrecht.code-block.margin-inline-start`
De volgende tokens zijn toegevoegd aan Figure component:
- …
> feat: margin tokens toegevoegd voor meerdere componenten - Voorbeeld
